### ISSUE TITLE
v0.1

### ISSUE THREAD

**Issue by fizruk** [dmjio/servant-swagger#1]
I am very interested in the first Hackage release of `servant-swagger`, but I am not sure what keeps it from happening and whether I can help it.
Can we write down the list of things to be done before the first release?

**Comment by dmjio** [comment]
I've been traveling for work. I can release a `v0` today if you'd like.
I'd still like to do the following.

- generics for swagger models 
- additional information for parameters. So a class for `ToSwaggerParam`, `ToSwaggerQueryParam`.
- documentation

In it's current state, servant-swagger is usable and I'm implementing it one of my projects for work. 

I will put up a `v0`.

**Comment by fizruk** [comment]
Yes, `v0` would be much appreciated!

Once it's out, I'll try it for my project and probably help you with some of the todos!

**Comment by dmjio** [comment]
It's up http://hackage.haskell.org/package/servant-swagger. This *API* will
change most likely. I want to add `ToSwaggerQueryParam` and
`ToSwaggerCapture` etc. So additional meta data can be captured that the
servant API doesn't include (like `enum`, and `required`, etc).

On Wed, Nov 4, 2015 at 9:54 AM, Nickolay Kudasov <notifications@github.com>
wrote:

> Yes, v0 would be much appreciated!
>
> Once it's out, I'll try it for my project and probably help you with some
> of the todos!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmjio/servant-swagger/issues/1#issuecomment-153771922>
> .
>



-- 
Cell: 1.630.740.8204

**Comment by fizruk** [comment]
Can you also expose `.Internal` module?

I would like to experiment with `servant-swagger` within my own project and I'd love to have access to things like e.g. `SwaggerRouteDescription` which is currently hidden from user.

The specific problem I am having right now is that I have sub APIs and it would be nice to have `SwaggerRouteInfo SubAPI` defined in `SubAPI` module (which does not know of `SuperAPI`) and then be able to use it to make `SwaggerRouteInfo SuperAPI`. Reality complicates things even further with multiple sub API layers.

Probably this problem should be discussed in a separate issue though.

**Comment by fizruk** [comment]
And I also would like `SwaggerAccept` to be exposed.

**Comment by dmjio** [comment]
@fizruk there might be some things I forgot to expose, like lenses etc.. Can you submit a pull exposing `SwaggerRouteDescription` and `SwaggerAccept` (and corresponding lenses)?

In regards to the `SubAPI` I ran into the same issue. I have an app that has the following setup:

```haskell
type API = LeftAPI :<|> RightAPI ....
type LeftAPI = A :<|> B
type RightAPI = C :<|> D
```

Since `SwaggerRouteInfo` is more or less the exact same thing as `ExtraInfo` for servant-docs I think we *have* to specify that `A` is in `API`. And it isn't possible to specify a description for `A` in `LeftAPI`.

**Comment by fizruk** [comment]
@dmjio we can select what should be exposed in `Servant.Swagger` later and simply expose `.Internal` module since it is The Right Thing To Do™ anyway.

I can probably think of a workaround for sub APIs, but later.

**Comment by dmjio** [comment]
This has been done, closing
