### ISSUE TITLE
Merge with swagger2

### ISSUE THREAD

**Issue by dmjio** [dmjio/servant-swagger#8]
@fizruk, stuck at an airport right now, but would like to begin this merger during the holidays 
:christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree: :christmas_tree:

**Comment by fizruk** [comment]
@dmjio I am ready to finally release `swagger2-1.0`, but would be glad if you glanced over the [release notes](https://github.com/GetShopTV/swagger2/blob/0ebf9318eb53fc387d91ebe13d1ad35dee7de618/CHANGELOG.md).

**Comment by fizruk** [comment]
[`swagger2-1.0`](http://hackage.haskell.org/package/swagger2-1.0) is out!

**Comment by dmjio** [comment]
The time has come :)

**Comment by fizruk** [comment]
@dmjio will you be available anytime soon to discuss our next steps?
